#!/bin/sh
python train_models.py --model_name=fireeye --input_size=204800 --window_size=500 --batch_size=32 --epochs=50 --lr=0.0001 --num_workers=4 --log_file_path=../../../elfsample/output.txt --checkpoint_dir=../../../elfsample/ --train_label_path=../../../elfsample/ELFDataset/TrainEven_Minus-All-Three_ELF_Dataset.csv --test_label_path=../../../elfsample/ELFDataset/TestEven_ELF_Dataset.csv --val_label_path=../../../elfsample/ELFDataset/ValidEven_ELF_Dataset.csv --all_file_path=../../../elfsample/ELFDataset/both/ &&
mv ../../../elfsample/fireeye_model.pth ../../../elfsample/fireeye_204800_minus-all-three_0001_500_32_model.pth &&
mv ../../../elfsample/output_fireeye.txt ../../../elfsample/fireeye_204800_minus-all-three_0001_500_32_output.txt &&
python train_models.py --model_name=fireeye --input_size=102400 --window_size=500 --batch_size=32 --epochs=50 --lr=0.0001 --num_workers=4 --log_file_path=../../../elfsample/output.txt --checkpoint_dir=../../../elfsample/ --train_label_path=../../../elfsample/ELFDataset/TrainEven_Minus-All-Three_ELF_Dataset.csv --test_label_path=../../../elfsample/ELFDataset/TestEven_ELF_Dataset.csv --val_label_path=../../../elfsample/ELFDataset/ValidEven_ELF_Dataset.csv --all_file_path=../../../elfsample/ELFDataset/both/ &&
mv ../../../elfsample/fireeye_model.pth ../../../elfsample/fireeye_102400_minus-all-three_0001_500_32_model.pth &&
mv ../../../elfsample/output_fireeye.txt ../../../elfsample/fireeye_102400_minus-all-three_0001_500_32_output.txt &&
python train_models.py --model_name=fireeye --input_size=204800 --window_size=500 --batch_size=32 --epochs=50 --lr=0.0001 --num_workers=4 --log_file_path=../../../elfsample/output.txt --checkpoint_dir=../../../elfsample/ --train_label_path=../../../elfsample/ELFDataset/TrainEven_Minus-Three_ELF_Dataset.csv --test_label_path=../../../elfsample/ELFDataset/TestEven_ELF_Dataset.csv --val_label_path=../../../elfsample/ELFDataset/ValidEven_ELF_Dataset.csv --all_file_path=../../../elfsample/ELFDataset/both/ &&
mv ../../../elfsample/fireeye_model.pth ../../../elfsample/fireeye_204800_minus-three_0001_500_32_model.pth &&
mv ../../../elfsample/output_fireeye.txt ../../../elfsample/fireeye_204800_minus-three_0001_500_32_output.txt &&
python train_models.py --model_name=fireeye --input_size=102400 --window_size=500 --batch_size=32 --epochs=50 --lr=0.0001 --num_workers=4 --log_file_path=../../../elfsample/output.txt --checkpoint_dir=../../../elfsample/ --train_label_path=../../../elfsample/ELFDataset/TrainEven_Minus-Three_ELF_Dataset.csv --test_label_path=../../../elfsample/ELFDataset/TestEven_ELF_Dataset.csv --val_label_path=../../../elfsample/ELFDataset/ValidEven_ELF_Dataset.csv --all_file_path=../../../elfsample/ELFDataset/both/ &&
mv ../../../elfsample/fireeye_model.pth ../../../elfsample/fireeye_102400_minus-three_0001_500_32_model.pth &&
mv ../../../elfsample/output_fireeye.txt ../../../elfsample/fireeye_102400_minus-three_0001_500_32_output.txt &&
python train_models.py --model_name=malconv --input_size=204800 --window_size=500 --batch_size=32 --epochs=50 --lr=0.0001 --num_workers=4 --log_file_path=../../../elfsample/output.txt --checkpoint_dir=../../../elfsample/ --train_label_path=../../../elfsample/ELFDataset/TrainEven_Minus-All-Three_ELF_Dataset.csv --test_label_path=../../../elfsample/ELFDataset/TestEven_ELF_Dataset.csv --val_label_path=../../../elfsample/ELFDataset/ValidEven_ELF_Dataset.csv --all_file_path=../../../elfsample/ELFDataset/both/ &&
mv ../../../elfsample/malconv_model.pth ../../../elfsample/malconv_204800_minus-all-three_0001_500_32_model.pth &&
mv ../../../elfsample/output_malconv.txt ../../../elfsample/malconv_204800_minus-all-three_0001_500_32_output.txt &&
python train_models.py --model_name=malconv --input_size=102400 --window_size=500 --batch_size=32 --epochs=50 --lr=0.0001 --num_workers=4 --log_file_path=../../../elfsample/output.txt --checkpoint_dir=../../../elfsample/ --train_label_path=../../../elfsample/ELFDataset/TrainEven_Minus-All-Three_ELF_Dataset.csv --test_label_path=../../../elfsample/ELFDataset/TestEven_ELF_Dataset.csv --val_label_path=../../../elfsample/ELFDataset/ValidEven_ELF_Dataset.csv --all_file_path=../../../elfsample/ELFDataset/both/ &&
mv ../../../elfsample/malconv_model.pth ../../../elfsample/malconv_102400_minus-all-three_0001_500_32_model.pth &&
mv ../../../elfsample/output_malconv.txt ../../../elfsample/malconv_102400_minus-all-three_0001_500_32_output.txt &&
python train_models.py --model_name=malconv --input_size=204800 --window_size=500 --batch_size=32 --epochs=50 --lr=0.0001 --num_workers=4 --log_file_path=../../../elfsample/output.txt --checkpoint_dir=../../../elfsample/ --train_label_path=../../../elfsample/ELFDataset/TrainEven_Minus-Three_ELF_Dataset.csv --test_label_path=../../../elfsample/ELFDataset/TestEven_ELF_Dataset.csv --val_label_path=../../../elfsample/ELFDataset/ValidEven_ELF_Dataset.csv --all_file_path=../../../elfsample/ELFDataset/both/ &&
mv ../../../elfsample/malconv_model.pth ../../../elfsample/malconv_204800_minus-three_0001_500_32_model.pth &&
mv ../../../elfsample/output_malconv.txt ../../../elfsample/malconv_204800_minus-three_0001_500_32_output.txt &&
python train_models.py --model_name=malconv --input_size=102400 --window_size=500 --batch_size=32 --epochs=50 --lr=0.0001 --num_workers=4 --log_file_path=../../../elfsample/output.txt --checkpoint_dir=../../../elfsample/ --train_label_path=../../../elfsample/ELFDataset/TrainEven_Minus-Three_ELF_Dataset.csv --test_label_path=../../../elfsample/ELFDataset/TestEven_ELF_Dataset.csv --val_label_path=../../../elfsample/ELFDataset/ValidEven_ELF_Dataset.csv --all_file_path=../../../elfsample/ELFDataset/both/ &&
mv ../../../elfsample/malconv_model.pth ../../../elfsample/malconv_102400_minus-three_0001_500_32_model.pth &&
mv ../../../elfsample/output_malconv.txt ../../../elfsample/malconv_102400_minus-three_0001_500_32_output.txt
